//
// Created by WYSJ6174 on 2021/9/25.
//

#ifndef INC_2021_FALL_BUAA_COMPILER_TECHNOLOGY_UTILS_H
#define INC_2021_FALL_BUAA_COMPILER_TECHNOLOGY_UTILS_H


class utils {

};


#endif //INC_2021_FALL_BUAA_COMPILER_TECHNOLOGY_UTILS_H
